//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK0401Pr2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductsMaterial = new HashSet<ProductsMaterial>();
        }
    
        public int ID { get; set; }
        public int IDMaterialTYpe { get; set; }
        public int IDUnitOfMeasurement { get; set; }
        public string NameMaterial { get; set; }
        public decimal UnitPriceOfMaterial { get; set; }
        public int QuantityInStock { get; set; }
        public int MinQuantity { get; set; }
        public int QuantityInPack { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterial> ProductsMaterial { get; set; }
    }
}
